routes/web.php
<?php

Route::group(['prefix' => 'admin'], function() {
    Route::resource('clientes', 'CustomersController');
});

Route::get('/', function () {
    $page = Bird\User::paginate(10);

    return Response::json([
        'draw' => $page->currentPage(),
        'recordsTotal' => $page->total(),
        'recordsFiltered' => $page->total(),
        'data' => $page = Bird\User::paginate(10)->toArray()['data']
    ]);
});

app/Customer.php
<?php

namespace Bird;

use Illuminate\Database\Eloquent\Model;
use Bird\Purchase;

class Customer extends Model
{
    protected $fillable = ['name', 'birthdate', 'special_customer', 'city', 'state'];

    protected $casts = [
        'special_customer' => 'boolean',
        'birthdate' => 'date',

    ];

        public function purchases()
    {
        return $this->hasMany(Purchases::class);
    }

}

app/Purchase.php
<?php

namespace Bird;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    //
}

app/User.php
<?php

namespace Bird;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace Bird\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomersController.php
<?php

namespace Bird\Http\Controllers;

use Illuminate\Http\Request;
use Bird\Customer;
use DB;

class CustomersController extends Controller
{

    public function index()
    {
        $customers = Customer::all();
        return view('customers.index')->with(compact('customers'));
    }


    public function create()
    {

    }


    public function store(Request $request)
    {
        $nome = $request->nome;
        $email = $request->email;
        $users = DB::table('customers')
                ->where('name', '=', $nome)
                ->get();
        dd($request->toArray());
    }


    public function show($id)
    {
        $customer = Customer::find($id);
        $customer->delete();
        return redirect('admin/clientes');
    }


    public function edit($id)
    {
        $customer = Customer::find($id);
        $customersForSelect = Customer::groupBy('state')->get(['state'])->pluck('state', 'state');
        return view('customers.edit')->with(compact('customer', 'customersForSelect'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'city' => 'required'
        ]);

        $input = $request->only('name', 'special_customer', 'city', 'state');
        $input['special_customer'] = isset($input['special_customer']);
        $customer = Customer::find($id);
        $customer->fill($input);
        $customer->save();
        return redirect()->route('clientes.edit', $id)->with(['success' => 'Cliente salvo com sucesso!']);
    }


    public function destroy($id)
    {
        $customer = Customer::find($id);
        $customer->delete();
        dd($customer);
    }
}

resources/views/customers/create.blade.php
@extends('layouts.main')

@section('page-title')
    Criar novo Cliente
@stop

@section('content')
    {!! Form::open(['url' => 'foo/bar']) !!}
        @include('customers.partials.form')
    {!! Form::close()!!}
@stop

resources/views/customers/edit.blade.php
@extends('layouts.main')

@section('page-title')
    Editar Cliente
@stop

@section('content')

    @if(count($errors->all()) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(Session::has('success'))
        <div class="alert alert-success">
            {{ Session::get('success')}}
        </div>
    @endif

    {!! Form::model($customer, ['route' => ['clientes.update', $customer->id]]) !!}
        <input type="hidden" name="_method" value="PUT">
        @include('customers.partials.form')
    {!! Form::close()!!}
@stop

resources/views/customers/index.blade.php
@extends('layouts.main')

@section('page-title')
    | Gerenciamento de Clientes
@stop

@section('content')
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Cidade/Estado</th>
                <th>Nascimento</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach($customers as $customer)
                <tr>
                    <td>{{ $customer->name }}</td>
                    <td>{{ $customer->city }}</td>
                    <td>{{ $customer->birthdate }}</td>
                    <td width="1%" nowrap>
                        <a href="{{ route('clientes.edit', $customer->id) }}" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-edit"></span></a>
                        <a href="{{ route('clientes.destroy', $customer->id) }}" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@stop

resources/views/customers/partials/form.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="from-group">
            {!! Form::label('name', 'Nome', array('class' => 'control-label')) !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="from-group">
            {!! Form::label('city', 'Cidade', array('class' => 'control-label')) !!}
            {!! Form::text('city', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="from-group">
            {!! Form::label('state', 'Estado', array('class' => 'control-label')) !!}
            {!! Form::select('state', $customersForSelect, null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="from-group">
            {!! Form::label('special_customer', 'Cliente Especial?', array('class' => 'control-label')) !!}
            {!! Form::checkbox('special_customer', $customer->special_customer, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary" style="margin-top: 10px">Salvar</button>
    </div>
</div>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Codecasts Laravel 5.3 @yield('page-title')</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Bem vindo ao mundo Laravel!</h1>
        @yield('content')
    </div>
</body>
</html>